language: python
python:
  - "3.6"
sudo: false

branches:
  only:
  - master
  - develop
install:
  - pip install -r scripts/requirements.txt
before_script:
  - chmod +x ./scripts/*.py
script:
  - python ./scripts/metadatacheck.py
